import { ThemeColors } from "../interface/Types";

export const colors = {
  primary: "#4c7f9c",
  light_sky: "#cae7f8",
  black: "#000",
  black_1: "#333",
  black_2: "#00000080",
  black_3: "#00000020",
  black_4: "#00000095",
  white: "#FFFFFF",
  white_1: "#f1f1f1",
  white_2: '#f0f0f0',
  white_3: "#ecebeb",
  light_white: "#ffffffbd",
  light_white_1: "#e0eff8",
  light_white_2: "#ffffff80",
  light_Gray: "#A9A9A9",
  light_gray_1:'#dcdcdc',
  light_gray_900: "rgba(255, 255, 255, 0.5)",
  gray: "#d3d3d3",
  gray_1: "#ddd",
  gray_2: "#EEE",
  gray_3: "#BCBCBC",
  black_900: "rgba(0,0,0,0.5)",
  balck_800: "rgba(0,0,0,0.4)",
  black_700: "rgba(0, 0, 0, 0.7)",
  dark_pink: "#a59db4",
  light_pink: "#dccfeb",
  light_pink_1: "#d2ced9",
  dark_pink_1: "#e9dffc",
  dark_gray: "#798c94",
  dark_gray_1: "#888",
  dark_gray_2: "#666",
  dark_gray_3: '#585858',
  blue: "#4A90E2",
  yellow: "#FFD700",
  light_yellow: '#f1e08a',
  dark_mauve: "#72616d",
  light_mauve: "#d2ced9",
  dark_mauve_1: "#49405b",
  dark_mauve_2: "#695c83",
  dark_mauve_3: "#695786",
  dark_mauve_4: "#352c44",
  green: "#1DB954",
  green_1: "#25D366",
};

export const pastelColors = ["#d7edf1", "#E8F5E9", "#fff1df", "#e2d3d3"];

export const courseThemes: { [key: string]: ThemeColors } = {
  default: {
    primaryColor: "#4A90E2",
    secondaryColor: "#CCFFFF",
    backgroundColor: "#FFFFFF",
    textColor: "#000000",
    accentColor: "#FFD700",
    headerColor: "#4A90E2",
    courseTitleColor: "#FFFFFF",
    instructorTextColor: "#FFFFFF",
    tabBackgroundColor: "#CCFFFF",
    dayBackgroundColor: "#F0FFFF",
    sectionBackgroundColor: "#F0FFFF",
    subsectionBackgroundColor: "#FFFFFF",
    lessonBackgroundColor: "#FFFFFF",
    reviewBackgroundColor: "#F8F8F8",
    descriptionColor: "#888888",
  },
  swaraYoga: {
    primaryColor: "#8e7f7d",
    secondaryColor: "#d6c6c2",
    backgroundColor: "#f9f2f2",
    textColor: "#8e7f7d",
    accentColor: "#f1e2e0",
    headerColor: "#8e7f7d",
    courseTitleColor: "#d6c6c2",
    instructorTextColor: "#f7ebea",
    tabBackgroundColor: "#d6c6c2",
    dayBackgroundColor: "#f1e2e0",
    sectionBackgroundColor: "#f1e2e0",
    subsectionBackgroundColor: "#f8eeed",
    lessonBackgroundColor: "#f8eeed",
    reviewBackgroundColor: "#f8eeed",
    descriptionColor: "#888",
  },
  meditation: {
    primaryColor: "#4A90E2",
    secondaryColor: "#CCFFFF",
    backgroundColor: "#FFFFFF",
    textColor: "#000000",
    accentColor: "#F0FFFF",
    headerColor: "#4A90E2",
    courseTitleColor: "#FFFFFF",
    instructorTextColor: "#FFFFFF",
    tabBackgroundColor: "#CCFFFF",
    dayBackgroundColor: "#F0FFFF",
    sectionBackgroundColor: "#F0FFFF",
    subsectionBackgroundColor: "#FFFFFF",
    lessonBackgroundColor: "#FFFFFF",
    reviewBackgroundColor: "#e0fffe",
    descriptionColor: "#888888",
  },
  restfulSleep: {
    primaryColor: "#4A90E2",
    secondaryColor: "#CCFFFF",
    backgroundColor: "#FFFFFF",
    textColor: "#000000",
    accentColor: "#F0FFFF",
    headerColor: "#4A90E2",
    courseTitleColor: "#FFFFFF",
    instructorTextColor: "#FFFFFF",
    tabBackgroundColor: "#CCFFFF",
    dayBackgroundColor: "#F0FFFF",
    sectionBackgroundColor: "#F0FFFF",
    subsectionBackgroundColor: "#e8eff6",
    lessonBackgroundColor: "#e8eff6",
    reviewBackgroundColor: "#f8f8f8",
    descriptionColor: "#888888",
  },
  breathwork: {
    primaryColor: "#4A90E2",
    secondaryColor: "#CCFFFF",
    backgroundColor: "#FFFFFF",
    textColor: "#000000",
    accentColor: "#F0FFFF",
    headerColor: "#4A90E2",
    courseTitleColor: "#FFFFFF",
    instructorTextColor: "#FFFFFF",
    tabBackgroundColor: "#CCFFFF",
    dayBackgroundColor: "#F0FFFF",
    sectionBackgroundColor: "#F0FFFF",
    subsectionBackgroundColor: "#FFFFFF",
    lessonBackgroundColor: "#FFFFFF",
    reviewBackgroundColor: "#f8f8f8",
    descriptionColor: "#888888",
  },
  blissCourse: {
    primaryColor: "#bd9028",
    secondaryColor: "#efe1c0",
    backgroundColor: "#f9f2f2",
    textColor: "#bd9028",
    accentColor: "#faf5e9",
    headerColor: "#bd9028",
    courseTitleColor: "#efe1c0",
    instructorTextColor: "#efe1c0",
    tabBackgroundColor: "#efe1c0",
    dayBackgroundColor: "#efe1c0",
    sectionBackgroundColor: "#efe1c0",
    subsectionBackgroundColor: "#faf5e9",
    lessonBackgroundColor: "#faf5e9",
    reviewBackgroundColor: "#faf5e9",
    descriptionColor: "#888",
  },
  ThirdEyeCourse: {
    primaryColor: "#bd9028",
    secondaryColor: "#efe1c0",
    backgroundColor: "#f9f2f2",
    textColor: "#bd9028",
    accentColor: "#faf5e9",
    headerColor: "#bd9028",
    courseTitleColor: "#efe1c0",
    instructorTextColor: "#efe1c0",
    tabBackgroundColor: "#efe1c0",
    dayBackgroundColor: "#efe1c0",
    sectionBackgroundColor: "#efe1c0",
    subsectionBackgroundColor: "#faf5e9",
    lessonBackgroundColor: "#faf5e9",
    reviewBackgroundColor: "#faf5e9",
    descriptionColor: "#888",
  },
};
